modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"

issueTrackerURL="https://github.com/MochiMochi-752/FutureTech/issues"

[[mods]]
modId="future_tech"
version="${mod_version}"
displayName="Future Tech"
logoFile= "logo.png"
authors="MochiMochi"
description='''aaa'''

#[[mixins]]
#config="${mod_id}.mixins.json"

[[dependencies.future_tech]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.future_tech]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
